steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: Update beer-pong-bot
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -x && \
        gcloud compute ssh bp-vm-instance-1 --zone=us-central1-c  --command='/bin/sh /home/bnatanelic/pull.sh'
