steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: Update staging server
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -x && \
        gcloud compute ssh --zone "us-central1-c" "bp-vm-instance-1"  --project "alpine-theory-363615" --command='/bin/sh /home/bnatanelic/pull.sh'
